language: python 

notifications:
    email: false

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew list python &>/dev/null || brew install python@3.8; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install pyenv-virtualenv; fi
jobs:
    include:
      - name: "Python 3.8.0 on Xenial Linux"
        python: 3.8
        install: 
            - pip install --upgrade pip  
            - pip install -r requirements.txt
            
        script: python -m py.test -s -v 

      - name: "Python 3.7.4 on macOS"
        os: osx
        osx_image: xcode12.2 
        language: shell
        python: 3.8
        install: 
            - pip3 install --upgrade pip  
            - pip3 install -r requirements.txt
            
        script: python3 -m py.test -s -v 
    #   - name: "Python 3.8.0 on Windows"
    #     os: windows           # Windows 10.0.17134 N/A Build 17134
    #     language: shell       # 'language: python' is an error on Travis CI Windows
    #     before_install:
    #       - choco install python --version 3.8.0
    #       - python -m pip install --upgrade pip
    #       - python --version
    #     env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

