language: python            # this works for Linux but is an error on macOS or Windows

cache: pip
install: 
    - pip install --upgrade pip  # all three OSes agree about 'pip3'
    - pip install -r requirements.txt
    

# 'python' points to Python 2.7 on macOS but points to Python 3.8 on Linux and Windows
# 'python3' is a 'command not found' error on Windows but 'py' works on Windows only
script: python -m py.test -s -v